-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 22:05:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema component_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema component_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `component_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `component_db` ;

-- -----------------------------------------------------
-- Table `component_db`.`component_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`component_types` (
  `component_type` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `component_type_description` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`component_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`components` (
  `component_id` INT UNSIGNED NOT NULL,
  `parent_component_id` INT UNSIGNED NULL,
  `component_type` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `angle_x` FLOAT NOT NULL,
  `angle_y` FLOAT NOT NULL,
  `angle_z` FLOAT NOT NULL,
  `scale_x` FLOAT NOT NULL,
  `scale_y` FLOAT NOT NULL,
  `scale_z` FLOAT NOT NULL,
  PRIMARY KEY (`component_id`),
  INDEX `component_type_idx` (`component_type` ASC) VISIBLE,
  CONSTRAINT `current_component_type`
    FOREIGN KEY (`component_type`)
    REFERENCES `component_db`.`component_types` (`component_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`mesh_component_informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`mesh_component_informations` (
  `mesh_component_id` INT UNSIGNED NOT NULL,
  `material_names` JSON NULL,
  INDEX `mesh_component_id_idx` (`mesh_component_id` ASC) VISIBLE,
  PRIMARY KEY (`mesh_component_id`),
  CONSTRAINT `mesh_component_id`
    FOREIGN KEY (`mesh_component_id`)
    REFERENCES `component_db`.`components` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`scenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`scenes` (
  `scene_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scene_description` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`scene_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`scene_informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`scene_informations` (
  `scene_information_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scene_id` INT UNSIGNED NOT NULL,
  `component_type` INT UNSIGNED NOT NULL,
  `component_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`scene_information_id`),
  INDEX `scene_id_idx` (`scene_id` ASC) VISIBLE,
  INDEX `component_type_idx` (`component_type` ASC) VISIBLE,
  INDEX `scene_component_id_idx` (`component_id` ASC) VISIBLE,
  CONSTRAINT `scene_id`
    FOREIGN KEY (`scene_id`)
    REFERENCES `component_db`.`scenes` (`scene_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scene_component_type`
    FOREIGN KEY (`component_type`)
    REFERENCES `component_db`.`component_types` (`component_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `scene_component_id`
    FOREIGN KEY (`component_id`)
    REFERENCES `component_db`.`components` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`skeletal_mesh_components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`skeletal_mesh_components` (
  `skeletal_mesh_component_id` INT UNSIGNED NOT NULL,
  `skeletal_mesh_name` VARCHAR(45) NULL,
  PRIMARY KEY (`skeletal_mesh_component_id`),
  CONSTRAINT `skeletal_mesh_component_id`
    FOREIGN KEY (`skeletal_mesh_component_id`)
    REFERENCES `component_db`.`mesh_component_informations` (`mesh_component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`static_mesh_components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`static_mesh_components` (
  `static_mesh_component_id` INT UNSIGNED NOT NULL,
  `static_mesh_name` VARCHAR(45) NULL,
  PRIMARY KEY (`static_mesh_component_id`),
  CONSTRAINT `static_mesh_component_id`
    FOREIGN KEY (`static_mesh_component_id`)
    REFERENCES `component_db`.`mesh_component_informations` (`mesh_component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`camera_component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`camera_component` (
  `camera_component_id` INT UNSIGNED NOT NULL,
  `width` SMALLINT(6) UNSIGNED NOT NULL,
  `height` SMALLINT(6) UNSIGNED NOT NULL,
  `near_z` FLOAT NOT NULL,
  `far_z` FLOAT NOT NULL,
  `fov_angle` FLOAT NOT NULL,
  PRIMARY KEY (`camera_component_id`),
  CONSTRAINT `camera_component_id`
    FOREIGN KEY (`camera_component_id`)
    REFERENCES `component_db`.`components` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
