-- MySQL Script generated by MySQL Workbench
-- Sun Feb  2 05:38:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema component_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema component_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `component_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `component_db` ;

-- -----------------------------------------------------
-- Table `component_db`.`components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`components` (
  `component_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_component_id` INT UNSIGNED NOT NULL DEFAULT '0',
  `component_name` VARCHAR(45) NOT NULL DEFAULT 'NULL',
  `position_x` FLOAT NOT NULL DEFAULT '0',
  `position_y` FLOAT NOT NULL DEFAULT '0',
  `position_z` FLOAT NOT NULL DEFAULT '0',
  `angle_x` FLOAT NOT NULL DEFAULT '0',
  `angle_y` FLOAT NOT NULL DEFAULT '0',
  `angle_z` FLOAT NOT NULL DEFAULT '0',
  `scale_x` FLOAT NOT NULL DEFAULT '0',
  `scale_y` FLOAT NOT NULL DEFAULT '0',
  `scale_z` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`component_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `component_db`.`camera_components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`camera_components` (
  `camera_component_id` INT UNSIGNED NOT NULL,
  `width` SMALLINT UNSIGNED NOT NULL,
  `height` SMALLINT UNSIGNED NOT NULL,
  `near_z` FLOAT NOT NULL,
  `far_z` FLOAT NOT NULL,
  `fov_angle` FLOAT NOT NULL,
  PRIMARY KEY (`camera_component_id`),
  CONSTRAINT `component_id_fk6`
    FOREIGN KEY (`camera_component_id`)
    REFERENCES `component_db`.`components` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `component_db`.`component_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`component_types` (
  `component_type` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `component_type_description` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`component_type`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `component_db`.`components_to_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`components_to_type` (
  `component_id` INT UNSIGNED NOT NULL,
  `component_type` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`component_id`),
  INDEX `components_to_type_comopnent_type_idx` (`component_type` ASC) VISIBLE,
  CONSTRAINT `component_type_fk1`
    FOREIGN KEY (`component_type`)
    REFERENCES `component_db`.`component_types` (`component_type`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `component_id_fk1`
    FOREIGN KEY (`component_id`)
    REFERENCES `component_db`.`components` (`component_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `component_db`.`mesh_component_informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`mesh_component_informations` (
  `mesh_component_id` INT UNSIGNED NOT NULL,
  `material_names` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`mesh_component_id`),
  INDEX `mesh_component_id_idx` (`mesh_component_id` ASC) VISIBLE,
  CONSTRAINT `component_id_fk3`
    FOREIGN KEY (`mesh_component_id`)
    REFERENCES `component_db`.`components` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `component_db`.`scenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`scenes` (
  `scene_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scene_description` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `scene_static_mesh_name` VARCHAR(45) NOT NULL,
  `scene_ibl_material_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`scene_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `component_db`.`scene_informations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`scene_informations` (
  `scene_information_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scene_id` INT UNSIGNED NOT NULL,
  `component_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`scene_information_id`),
  INDEX `scene_id_idx` (`scene_id` ASC) VISIBLE,
  INDEX `scene_component_id_idx` (`component_id` ASC) VISIBLE,
  CONSTRAINT `component_id_fk2`
    FOREIGN KEY (`component_id`)
    REFERENCES `component_db`.`components` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `scene_id_fk1`
    FOREIGN KEY (`scene_id`)
    REFERENCES `component_db`.`scenes` (`scene_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `component_db`.`skeletal_mesh_components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`skeletal_mesh_components` (
  `skeletal_mesh_component_id` INT UNSIGNED NOT NULL,
  `skeletal_mesh_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`skeletal_mesh_component_id`),
  CONSTRAINT `component_id_fk4`
    FOREIGN KEY (`skeletal_mesh_component_id`)
    REFERENCES `component_db`.`mesh_component_informations` (`mesh_component_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `component_db`.`static_mesh_components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`static_mesh_components` (
  `static_mesh_component_id` INT UNSIGNED NOT NULL,
  `static_mesh_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`static_mesh_component_id`),
  CONSTRAINT `component_id_fk5`
    FOREIGN KEY (`static_mesh_component_id`)
    REFERENCES `component_db`.`mesh_component_informations` (`mesh_component_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_520_ci;


-- -----------------------------------------------------
-- Table `component_db`.`collision_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`collision_options` (
  `collision_option_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `collision_option_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`collision_option_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`sphere_collision_components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`sphere_collision_components` (
  `sphere_collision_component_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `radius` FLOAT NOT NULL,
  `collision_option_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sphere_collision_component_id`),
  INDEX `collision_option_fk1_idx` (`collision_option_id` ASC) VISIBLE,
  CONSTRAINT `component_id_fk7`
    FOREIGN KEY (`sphere_collision_component_id`)
    REFERENCES `component_db`.`components` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `collision_option_fk1`
    FOREIGN KEY (`collision_option_id`)
    REFERENCES `component_db`.`collision_options` (`collision_option_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`oriented_box_collision_components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`oriented_box_collision_components` (
  `oriented_box_collision_component_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `extent_x` FLOAT NOT NULL,
  `extent_y` FLOAT NOT NULL,
  `extent_z` FLOAT NOT NULL,
  `collision_option_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`oriented_box_collision_component_id`),
  INDEX `collision_option_fk2_idx` (`collision_option_id` ASC) VISIBLE,
  CONSTRAINT `component_id_fk8`
    FOREIGN KEY (`oriented_box_collision_component_id`)
    REFERENCES `component_db`.`components` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `collision_option_fk2`
    FOREIGN KEY (`collision_option_id`)
    REFERENCES `component_db`.`collision_options` (`collision_option_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_db`.`lights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_db`.`lights` (
  `light_component_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `light_power` FLOAT NOT NULL,
  `falloff_start` FLOAT NOT NULL,
  `falloff_end` FLOAT NOT NULL,
  `spot_power` FLOAT NOT NULL,
  PRIMARY KEY (`light_component_id`),
  CONSTRAINT `component_id_fk9`
    FOREIGN KEY (`light_component_id`)
    REFERENCES `component_db`.`components` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
