#pragma once
enum class EComponentType
{
	NOT_SELECTED,
	STATIC_COMPONENT,
	SKELETAL_COMPONENT,
	CAMERA_COMPONENT,
	SPHERE_COLLISION_COMPONENT,
	ORIENTED_BOX_COLLISION_COMPONENT,
	SPOT_LIGHT_COMPONENT,
	POINT_LIGHT_COMPONENT
};

enum class ECollisionOptionType
{
	NOT_SELECTED,
	RENDER_CONTROL
};
